# -*- mode:org; mode:auto-fill; fill-column:80; coding:utf-8; tab-width:8; -*-
VobSub2SRT is a simple command line program to convert =.idx= / =.sub= subtitles
into =.srt= text subtitles by using OCR.  It is based on code from the
[[https://www.mplayerhq.hu][MPlayer project]] - a pretty decent movie player.  Some minor parts are
 copied from [[https://ffmpeg.org/][ffmpeg/avutil]] headers. [[https://code.google.com/p/tesseract-ocr/][Tesseract]] is used as OCR software. [[https://opencv.org/][OpenCV]] is used for contour detection to help detect italic characters and to manipulate subtitle images.

vobsub2srt is released under the GPL3+ license. The MPlayer code included is
GPL2+ licensed.

The quality of the OCR depends on the text in the subtitles.

** September 2026
New:
- Option for Italic text detection and <i>text</i> tags in the .SRT file
- Option for batch OCR: combine subtitle images for better OCR results
- Automatic threshold limit detection to prepare image for better results with
  Tesseract, based on color (grayscale) histogram.
- Add borders to image for better results with Tesseract
- Option to limit subtitle display duration to base duration + (length / chars-per-sec)
- Bugfix for mplayer code that resulted in broken palette and broken image
- Bugfix for skipped subtitle images

* Building
You need OpenCV, Tesseract, CMake and GCC to build =vobsub2srt=.
With a Debian-based distribution, you can install the dependencies with:

#+BEGIN_EXAMPLE
  sudo apt-get install libopencv-dev libtiff5-dev libtesseract-dev build-essential cmake pkg-config
#+END_EXAMPLE

You also need to install the tesseract data for the languages you want to use:

#+BEGIN_EXAMPLE
	sudo apt-get install tesseract-lang-eng
#+END_EXAMPLE

#+BEGIN_EXAMPLE
  ./configure
  make
  sudo make install
#+END_EXAMPLE

Note that support for Tesseract <4 is deprecated.

Building from NixOS (Tested with 26.05):
#+BEGIN_EXAMPLE
nix-env -iA nixos.git nixos.gcc nixos.cmake nixos.tesseract nixos.libtiff nixos.libpng nixos.zlib
git clone https://github.com/csingleplus/VobSub2SRT && cd VobSub2SRT
cmake -B build
cmake --build build
sudo cmake --install build
#+END_EXAMPLE

This should install the program vobsub2srt to =/usr/local/bin=.
Run configure with -DCMAKE_INSTALL_PREFIX=<path> for elsewhere. You can
uninstall vobsub2srt with =sudo make uninstall=.

*** .deb (Debian/Ubuntu)
You can build a *.deb package (Debian/Ubuntu) with =make package=.  The package
is created in the =build= directory.


* Usage
vobsub2srt converts subtitles in VobSub (=.idx= / =.sub=) format into subtitles
in =.srt= format.  VobSub subtitles consist of two or three files called
=Filename.idx=, =Filename.sub= and optional =Filename.ifo=. To convert subtitles
simply call

#+BEGIN_EXAMPLE
  vobsub2srt Filename
#+END_EXAMPLE

with =Filename= being the file name of the subtitle files *WITHOUT* the
extension (=.idx= / =.sub=). vobsub2srt writes the subtitles to a file called
=Filename.srt=. You can see the subtitles as they are decoded with =--show=.

If a subtitle file contains more than one language you can use the =--lang=
parameter to set the correct language (Use =--langlist= to find out about the
languages in the file).  For some languages you might need to set the tesseract
language yourself (e.g., chi_tra/chi_sim for traditional or simplified chinese
characters).  You can use =--tesseract-lang= to do this. Multilingual subtitles
may be written by combining langcodes as such: eng+fra. In most cases this
should however be autodetected.

If you want to dump the subtitles as images (e.g. to check for correct ocr) you
can use the =--dump-images= flag.

Use =--help= or read the manpage to get more information about the options of
vobsub2srt.

A more elaborate example:

Input files:

#+BEGIN_EXAMPLE
my-movie-subtitle.idx
my-movie-subtitle.sub
#+END_EXAMPLE

Command:

#+BEGIN_EXAMPLE
  vobsub2srt --detect-italic --base-duration 1500 --chars-per-sec 19 --tesseract-lang 'eng+fra' my-movie-subtitle
#+END_EXAMPLE

Output file:

#+BEGIN_EXAMPLE
my-movie-subtitle.srt
#+END_EXAMPLE

Example contents of the .srt file:

#+BEGIN_EXAMPLE
...

199
00:50:01,230 --> 00:50:03,221
- No.
- <i>Non?</i>

...
#+END_EXAMPLE


* Bug reports
Please submit bug reports or feature requests to the
[[https://github.com/wififreedom/VobSub2SRT/issues][issue tracker on GitHub]].

If you have problems with a specific subtitle file then please check if
it works in mplayer first. Also, you may need to replace the palette line
in your .idx file to this, a plain white-on-black palette for better accuracy.

#+BEGIN_SRC
	palette: 000000,ffffff,000000,000000,000000,ffffff,000000,000000,000000,ffffff,000000,000000,000000,ffffff,000000,000000
#+END_SRC

For bug reports please run =vobsub2srt= with the =--verbose= option set to 2,
and copy and paste the first 50~ lines from the beginning of the problem to the bug report.
