name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: update-apt
      run: sudo apt update
    - name: install-deps
      run: sudo apt install libtesseract-dev tesseract-ocr-eng g++ gcc cmake -y
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make install
      run: sudo make install
    - name: vobsub2srt-runtest
      run: vobsub2srt --help
